{ config, lib, pkgs, options, ... }: {
  imports = [ ./modules.nix ];
  
  config.homebrew.casks = [        
    "appcleaner"
    "balenaetcher"
    "bitwig-studio"
    "blender"
    "charles"
    "disk-drill"
    "firefox"
    "gimp"
    "grandperspective"
    "handbrake"
    "inkscape"
    "karabiner-elements"
    "krita"
    "launchcontrol"
    "little-snitch"
    "musescore"
    "nomachine"
    "obs"
    "protonmail-bridge"
    "protonvpn"
    "resilio-sync"
    "spotify"
    "transmission"
    "visual-studio-code"
    "vlc"
    "zed@preview"
    # "brave-browser"
    # "chromium"
    # "cold-turkey-blocker"
    # "contexts"
    # "darktable"
    # "dash"
    # "discord"
    # "docker"
    # "element"
    # "geekbench"
    # "iterm2"
    # "libreoffice"
    # "obsidian"
    # "openvpn-connect"
    # "the-unarchiver"
    # "wireshark"
    # "zenmap"
  ];
}
